name: geollm
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>3.10,<3.12
  - jupyter>=1.0
  - jupyterlab>=4.0.11
  - ipywidgets>=8.1.1
  - nodejs>16.14
  - black>22.10.0
  - blackd>22.10.0
  - isort>5.10.1
  - jupyterlab_code_formatter>1.6.1
  - langchain>=0.1.0
  - transformers>=4.35.2
  - openai>=1.6.1
  - bs4>=4.12.2
  - tiktoken>=0.5.2
  - deepdiff>=6.7.1
  - pydantic
  - numpydoc
  - faiss-cpu
  - accelerate>=0.26.1
  - numexpr>=2.8.8
  - ollama
  - pip
  - pip:
      - langchainhub
      - langchain-mistralai
      - langchain-openai
      - langchain-experimental
