name: geollm
channels:
  - conda-forge
dependencies:
  - python<3.11
  - python-multipart>=0.0.6
  - fastapi>0.101.1
  - jupyter>=1.0
  - jupyterlab>4.0
  - nodejs>16.14
  - geopandas>0.12.2
  - contextily>1.1
  - ipyleaflet>0.17.2
  - gdal>3.8
  - pyarrow>1.0
  - black>22.10.0
  - blackd>22.10.0
  - isort>5.10.1
  - jupyterlab_code_formatter>1.6.1
  - langchain>=0.0.190
  - pyspark>3.4.0,<3.5.0
  - pip
  - pip:
      - fastapi-sessions>=0.3.2
